Sylius 1.13 and Symfony Workflow support
monsieurbiz/SyliusOrderHistoryPlugin pull request #7
Opened 2024-10-01 11:13 UTC by coldic3

I upgraded to Sylius 1.13, which now supports Symfony Workflow, so I've added support for it here as well :woman_dancing:

2025-01-14 15:37 UTC, lanfisis commented
Hello @coldic3. Thanks for this PR, and sorry for the long response time. Would you rebase your branch please and resolve the branch conflict before I made a review please ?

2025-05-05 14:15 UTC, lanfisis requested changes
You have to rebase your PR

2025-05-07 06:16 UTC, coldic3 commented
Hey @lanfisis, I've rebased the PR and resolved the conflicts.

2025-05-22 07:02 UTC, delyriand approved these changes

2025-05-23 08:09 UTC, lanfisis approved these changes

2025-05-23 08:10 UTC, merged